AWSTemplateFormatVersion: '2010-09-09'
Description: ACG AWS CodeDeploy VPC

Parameters:

  YourName:
    Description: Prefix to keep names unique
    Type: String

  VPCIP:
    Type: Number
    Description: X in 10.X.0.0/16
    Default: 42
    MinValue: 0
    MaxValue: 255

Resources:

#
# VPC
#

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Join [".", ["10", !Ref VPCIP, "0.0/16"]]
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref YourName, "vpc"]]

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref YourName, "igw"]]

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

#
# Public Route Table
#

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: InternetGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref YourName, "public"]]

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

#
# Public Subnet NACL
#

  PublicNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref YourName, "public"]]

  InboundNACLEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNetworkAcl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: "-1"
        Type: "-1"

  OutboundNACLEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref PublicNetworkAcl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: 0.0.0.0/0
      Icmp:
        Code: "-1"
        Type: "-1"

#
# Availability Zone A
#

  SubnetPublicA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs ]
      MapPublicIpOnLaunch: true
      CidrBlock: !Join [".", ["10", !Ref VPCIP, "10.0/24"]]
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref YourName, "public", "a"]]

  SubnetPublicANACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PublicNetworkAcl
      SubnetId: !Ref SubnetPublicA

  SubnetPublicARouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetPublicA

#
# Availability Zone B
#

  SubnetPublicB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs ]
      MapPublicIpOnLaunch: true
      CidrBlock: !Join [".", ["10", !Ref VPCIP, "20.0/24"]]
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref YourName, "public", "b"]]

  SubnetPublicBNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PublicNetworkAcl
      SubnetId: !Ref SubnetPublicB

  SubnetPublicBRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetPublicB

#
# Availability Zone C
#

  SubnetPublicC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 2, !GetAZs ]
      MapPublicIpOnLaunch: true
      CidrBlock: !Join [".", ["10", !Ref VPCIP, "30.0/24"]]
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref YourName, "public", "c"]]

  SubnetPublicCNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId: !Ref PublicNetworkAcl
      SubnetId: !Ref SubnetPublicC

  SubnetPublicCRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref SubnetPublicC

Outputs:

  VPCID:
    Description: VPC ID
    Value: !Ref VPC

  SubnetsPublic:
    Description: Public Subnets
    Value: !Join [",", [!Ref SubnetPublicA, !Ref SubnetPublicB, !Ref SubnetPublicC]]

  AZs:
    Description: Availability Zones
    Value : !Join [",", [!Select [ 0, !GetAZs ], !Select [ 1, !GetAZs ], !Select [ 2, !GetAZs ]]]